### ISSUE TITLE
What is your working environment at Codeschool?

### ISSUE THREAD

**Issue by oxfist** [olivierlacan/ask#1]
What kind of computer and OS do you guys use? Also, what technologies do you use on a daily basis? E-mail, project management app, programming languages, frameworks, etc. Finally, do people get to work at Codeschool being already profficient in some programming language or do you guys kind of build up?

**Comment by olivierlacan** [comment]
**What kind of computer and OS do you guys use?**
Overwhelmingly we use Macs. I think it's mostly a split between MacBook Airs (13") and Retina MacBook Pro (13" and 15"). There are also some older non-Retina MacBook Pros (developers and office laptops). We have one or two Mac Minis around the office of iOS testing, and to power our two [information radiators](http://agile-wiki.wikispaces.com/Information+radiators) (very large, always-on, airport-grade LCD displays). We also have two iMacs for pairing (or to use as an external screen). I set one of them up as a sort of [HoloDeck](http://en.wikipedia.org/wiki/Holodeck) that allows people who can't be in the office to see and talk to each other and anyone in front of that specific iMac. It's really neat and we use [VLine](https://vline.com/) (a free WebRTC service), a Logitech C920 HD webcam and an MXL AC404 omnidirectional microphone to capture people talking far away from the screen without too much noise.

There are a few people in Sales & Marketing using Windows laptops because they need a specific version of Excel to run numbers and simulations but they do so begrudgingly. We have a single Linux user, Thomas who does a lot of [SysAdmin](http://en.wikipedia.org/wiki/System_administrator) and doesn't care much for Apple products. Several of us have gaming PCs at home, but otherwise we don't touch Microsoft software with a ten foot pole, unless it's on a gaming console.

As far as OSes, I'd say most of us are on OS X 10.9 by now but there might be a few people still stuck on 10.8.

**Also, what technologies do you use on a daily basis?**

Phew, that might take a while.
- Email: Mail.app, Airmail
- Project Management: Basecamp, GitHub, Email, HipChat
- Programming Languages: Ruby, JavaScript, CoffeeScript, Shell
- Frameworks: Rails, Angular, jQuery, Ember, Backbone

**Do people get to work at Codeschool being already profficient in some programming language or do you guys kind of build up?**

Most developers need to be proficient with Ruby before they join our team because we use it for so many things. Since we deal with the web, JavaScript is an obvious second although some of us prefer to work with CoffeeScript.

Let me know if you have more specific questions. :smiley:

**Comment by oxfist** [comment]
Is there any particular reason in going the Mac way? What is the argument in that? 'because costs are way high so I'm guessing it's not a money saving decision.

Also, to my understanding, Angular.js, Ember.js and Backbone.js are equivalent technologies, aren't they? So how come you guys use all of them on a daily basis? I would've thought that you kind of focused on one of them because it seems to me that that's like developing with Zend AND Symfony2 like at the same time (but in different projects).

**Comment by lozandier** [comment]
@oxfist When it comes to Macs and the Macbook Pro, the OS is a key reason to have them and they're exclusive to Macs. 

 The OS allow you to tap into a pipeline of dedicated apps towards better design and development while still allowing you to have a POSIX compliant terminal. 

The OS can practically do everything in the terminal you can do Linux OSes such as Ubuntu (I wouldn't wish Windows' command line on my worst enemy to do productive dev work) while still having the support of mainstream apps that have no choice to be on both Windows and Mac due to the fact both OSes are popular by their targeted audiences.  

High quality apps dedicated to productivity in the industry such as Sketch are exclusive on Macs and Macbook Pros.

Finally, the OS has dedicated features that appeal to designers and developers such as being able to preview entire sequences of image media is invaluable and using special characters rapidly that's not done on Windows or a flavor of Linux (or as well). 

The alternative is Linux while Windows is rather a eccentric choice for a web developer unless that web developer develops using Microsoft's proprietary languages/platforms like asp.net. 

In addition to the OS, Macs (and Macbook Pros) are better designed than an overwhelming amount of computers for web designers and web developers and their workspaces. 

## Regarding JavaScript frameworks,

 Angular.js, Ember.js and Backbone.js are absolutely _not_  Each framework has its strengths and weaknesses, and you may have to deviate from one to use another one depending on what you're trying to accomplish, what built-in tools they have to work for specific problems or environments easier, and so on.
