### ISSUE TITLE
What are some mild cheeses I should try with red wine?

### ISSUE THREAD

**Issue by jamesmichiemo** [olivierlacan/ask#2]

**Comment by twinn** [comment]
+1

**Comment by olivierlacan** [comment]
First, you're doing it wrong. Red wine is a strong flavor, it needs to be paired with a strong dish. 

When you pair wines with a course you tend to do it with earthy strong flavors like beef, potatoes, things that won't get overwhelmed and silenced by the red bitterness.

So no, I will not give you mild cheese advice because mild cheese is for wusses. Instead you go ahead and grab a good piece of bread (baguette or Italian ciabatta will do, Levain or Sourdough if you must) and on it, slap a teaspoon-sized piece of:

## St Marcelin

![](http://www.artisanalcheese.com/images/pc-10635.jpg)
Really easy to find at Whole Foods. You can have it cold or slightly warmed up. Although people seem to enjoy it warm I prefer my cheese at room temperature, except for goat cheese or creamy cow milk cheese that needs to be fresh.

## St Félicien

![](http://upload.wikimedia.org/wikipedia/commons/5/59/Saint-Felicien.jpg)
Softer and less melty than St Marcelin, while a little more bitter on the end. Which means it goes well with stronger red wine.

## Fourme d'Ambert

![](http://www.artisanalcheese.com/images/10229.jpg)
This is the creamiest and only blue cheese you should ever have. I've never met a Bleu d'Auvergne or Roquefort I've liked whereas it's really hard to find some bad Fourme d'Ambert. You can find this at Whole Foods regularly.

## St Nectaire Fermier

![](http://www.frenchcheeseclub.com/products/imagedischamp/stnectaire.jpg)
A childhood favorite for me, it's super hard to find in the US in its "Fermier" style since I'm pretty sure that would be unpasteurized (and therefore bland as fuck), but if you can find some, holy shit. Make sure to let it age (in a cold, damp, cool place) before you eat it. It's even better when it ages.

There are a lot more cheeses I would recommend, but specifically paired with red wine (which I've only come to appreciate lately) these are my favorite.

**Comment by mcansky** [comment]
wow

> I've never met a Bleu d'Auvergne or Roquefort

well, that's more Roquefort for me then.

Yet I have to agree, the Fourme d'Ambert is usually better than the Bleu d'Auvergne.

**Comment by jamesmichiemo** [comment]
I'm really enjoying all of the cheeses Olivier suggested except I can't find any St Félician. I'll have to look a bit harder for that one.

**Comment by olivierlacan** [comment]
Go to La Femme du Fromage at East End Market or email her and order some. Say I sent you and I bet she'll find a way to get you some even though it's not _that_ rare. 

Otherwise I could sneak one past the border whenever I fly back. 

That would be a cool way to be deported for not declaring illegal agricultural goods.

**Comment by mcansky** [comment]
@olivierlacan ever tried UK's Stilton ?

It's supposed to be nice with a glass of red porto.

**Comment by olivierlacan** [comment]
@mcansky Honestly I'm not a big fan of most UK and US cheeses because most of them feel like vaguely modified versions of the same cheese and I like to feed the stereotype that French people hate Brits because what little food I had in London was mostly awful (excepts the sweets).

I should really look into them seriously but they're probably harder to find in the US and/or France.

**Comment by mcansky** [comment]
ok :)
