### ISSUE TITLE
Are there any good baguettes in Orlando?

### ISSUE THREAD

**Issue by nselikoff** [olivierlacan/ask#3]
I miss being able to pop downstairs from our apartment in Paris, down a few doors to a boulangerie, and pick up a freshly baked, warm, crispy-on-the-outside and slightly-doughy-on-the-inside "baguette de tradition française". Did you ever encounter anything even close to that in Orlando?

**Comment by olivierlacan** [comment]
Yes there are.

The absolute best in my mind is [Benjamin French Bakery & Café](http://www.benjaminfrenchbakery.com/) in Thornton Park (close to Dexter's). It's owned by a French family from Bordeaux and they make delicious baguette sandwiches (which they call "Rustic Sandwiches"). Make sure to tell them not to toast the stuff because most Americans don't have the robust gums of weathered French baguette veterans. They also have nice pastries, quiches, etc.

The second best (at a safe distance) would be [Old Hearth Bread Company](http://oldehearthbreadcompany.com/) at East End Market. They have an insanely great selection of breads so I wouldn't just limit myself to their baguette which is a bit too tough for my preference. They also have delicious Levain (buckwheat rising dough), Sourdough, Ciabatta. Their dry pastries (Croissant, Pain au Chocolat) are also delicious.

Finally I don't want to leave out [Croissant Gourmet](https://www.facebook.com/pages/Croissant-Gourmet/173255196018335?fref=ts) in Winter Park because the owner is from Lille, France and I'm there right now. He's a master pastry chef and his pastries rival the best stuff you can get in Paris. His baguettes are much too flaky and the inside too light and bleached for my liking, but it's still better than most baguettes you can find around town. Remember that Pastry and Bakery are often practiced by two different people (even inside the same bakery) so it's always best to figure out what they specialize in.
